backend:
  name: github
  repo: NoroffFEU/musikkforandrerliv.no
  branch: develop
  # local_backend: true

  commit_messages:
    create: "Create {{collection}} entry: '{{slug}}'"
    update: "Update {{collection}} entry: '{{slug}}'"
    delete: "Delete {{collection}} entry: '{{slug}}'"
    uploadMedia: "Upload media file: '{{path}}'"
    deleteMedia: "Delete media file: '{{path}}'"

media_folder: 'content/gallery'

collections:
  - name: 'contents'
    label: 'Contents'
    files: 
      - label: "English"
        name: "en"
        file: "public/locales/locales.en.json"
        fields:
          - { name: 'home', label: 'Home Page', widget: 'object',
              fields: [
                { label: 'Title', name: 'title', widget: 'string', required: false },
                { label: 'Intro', name: 'intro', widget: 'markdown', required: false },
                { label: 'Hero Image', name: 'hero_image', widget: 'image', required: false },
                { label: 'Call to Action Text', name: 'cta_text', widget: 'string', required: false },
                { label: 'Main Content', name: 'main_content', widget: 'markdown', required: false }
              ] 
            }
          - { name: 'about', label: 'About Us Page', widget: 'object',
              fields: [
                { label: 'Title', name: 'title', widget: 'string', required: false },
                { label: 'Description', name: 'description', widget: 'text', required: false },
                { label: 'Contact Form Success Message', name: 'contact_form_success_message', widget: 'string', required: false },
                { label: 'Contact Form Error Message', name: 'contact_form_error_message', widget: 'string', required: false },
                { label: 'Contact Info Address', name: 'contact_info_address', widget: 'text', required: false },
                { label: 'Contact Info Phone', name: 'contact_info_phone', widget: 'number', required: false }
              ] 
            }
          - { label: 'Our Work Page', name: 'our_work', widget: 'object',
              fields: [
                { label: 'Title', name: 'title', widget: 'string', required: false },
                { label: 'Date', name: 'date', widget: 'datetime', required: false },
                { label: 'Description', name: 'description', widget: 'markdown', required: false },
                { label: 'Participants', name: 'participants', widget: 'list', field: { label: 'Name', name: 'name', widget: 'string', required: false }, required: false },
                { label: 'Results', name: 'results', widget: 'markdown', required: false }
              ] 
            }
          - { label: 'Blog', name: 'blog', widget: 'object',
              fields: [
                { label: 'Title', name: 'title', widget: 'string', required: false },
                { label: 'Publish date', name: 'date', widget: 'datetime', required: false },
                { label: 'Author', name: 'author', widget: 'string', required: false },
                { label: 'Excerpt', name: 'excerpt', widget: 'text', required: false },
                { label: 'Content', name: 'content', widget: 'markdown', required: false },
                { label: 'Tags', name: 'tags', widget: 'list', field: { name: 'tag', widget: 'string', required: false }, required: false }
              ] 
            }
      - label: "Malagasy"
        name: "mg"
        file: "public/locales/locales.mg.json"
        fields:
          - { name: 'home', label: 'Home Page', widget: 'object',
              fields: [
                { label: 'Title', name: 'title', widget: 'string', required: false },
                { label: 'Intro', name: 'intro', widget: 'markdown', required: false },
                { label: 'Hero Image', name: 'hero_image', widget: 'image', required: false },
                { label: 'Call to Action Text', name: 'cta_text', widget: 'string', required: false },
                { label: 'Main Content', name: 'main_content', widget: 'markdown', required: false }
              ] 
            }
          - { name: 'about', label: 'About Us Page', widget: 'object',
              fields: [
                { label: 'Title', name: 'title', widget: 'string', required: false },
                { label: 'Description', name: 'description', widget: 'text', required: false },
                { label: 'Contact Form Success Message', name: 'contact_form_success_message', widget: 'string', required: false },
                { label: 'Contact Form Error Message', name: 'contact_form_error_message', widget: 'string', required: false },
                { label: 'Contact Info Address', name: 'contact_info_address', widget: 'text', required: false },
                { label: 'Contact Info Phone', name: 'contact_info_phone', widget: 'number', required: false }
              ] 
            }
          - { label: 'Our Work Page', name: 'our_work', widget: 'object',
              fields: [
                { label: 'Title', name: 'title', widget: 'string', required: false },
                { label: 'Date', name: 'date', widget: 'datetime', required: false },
                { label: 'Description', name: 'description', widget: 'markdown', required: false },
                { label: 'Participants', name: 'participants', widget: 'list', field: { label: 'Name', name: 'name', widget: 'string', required: false }, required: false },
                { label: 'Results', name: 'results', widget: 'markdown', required: false }
              ] 
            }
          - { label: 'Blog', name: 'blog', widget: 'object',
              fields: [
                { label: 'Title', name: 'title', widget: 'string', required: false },
                { label: 'Publish date', name: 'date', widget: 'datetime', required: false },
                { label: 'Author', name: 'author', widget: 'string', required: false },
                { label: 'Excerpt', name: 'excerpt', widget: 'text', required: false },
                { label: 'Content', name: 'content', widget: 'markdown', required: false },
                { label: 'Tags', name: 'tags', widget: 'list', field: { name: 'tag', widget: 'string', required: false }, required: false }
              ] 
            }
      - label: "Norwegian"
        name: "no"
        file: "public/locales/locales.no.json"
        fields:
          - { name: 'home', label: 'Home Page', widget: 'object',
              fields: [
                { label: 'Title', name: 'title', widget: 'string', required: false },
                { label: 'Intro', name: 'intro', widget: 'markdown', required: false },
                { label: 'Hero Image', name: 'hero_image', widget: 'image', required: false },
                { label: 'Call to Action Text', name: 'cta_text', widget: 'string', required: false },
                { label: 'Main Content', name: 'main_content', widget: 'markdown', required: false }
              ] 
            }
          - { name: 'about', label: 'About Us Page', widget: 'object',
              fields: [
                { label: 'Title', name: 'title', widget: 'string', required: false },
                { label: 'Description', name: 'description', widget: 'text', required: false },
                { label: 'Contact Form Success Message', name: 'contact_form_success_message', widget: 'string', required: false },
                { label: 'Contact Form Error Message', name: 'contact_form_error_message', widget: 'string', required: false },
                { label: 'Contact Info Address', name: 'contact_info_address', widget: 'text', required: false },
                { label: 'Contact Info Phone', name: 'contact_info_phone', widget: 'number', required: false }
              ] 
            }
          - { label: 'Our Work Page', name: 'our_work', widget: 'object',
              fields: [
                { label: 'Title', name: 'title', widget: 'string', required: false },
                { label: 'Date', name: 'date', widget: 'datetime', required: false },
                { label: 'Description', name: 'description', widget: 'markdown', required: false },
                { label: 'Participants', name: 'participants', widget: 'list', field: { label: 'Name', name: 'name', widget: 'string', required: false }, required: false },
                { label: 'Results', name: 'results', widget: 'markdown', required: false }
              ] 
            }
          - { label: 'Blog', name: 'blog', widget: 'object',
              fields: [
                { label: 'Title', name: 'title', widget: 'string', required: false },
                { label: 'Publish date', name: 'date', widget: 'datetime', required: false },
                { label: 'Author', name: 'author', widget: 'string', required: false },
                { label: 'Excerpt', name: 'excerpt', widget: 'text', required: false },
                { label: 'Content', name: 'content', widget: 'markdown', required: false },
                { label: 'Tags', name: 'tags', widget: 'list', field: { name: 'tag', widget: 'string', required: false }, required: false }
              ] 
            }